/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    projects: Project;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    pages: Page;
    'home-page': HomePage;
    'about-page': AboutPage;
    'contact-page': ContactPage;
    'services-index-page': ServicesIndexPage;
    'portfolio-index-page': PortfolioIndexPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'services-index-page': ServicesIndexPageSelect<false> | ServicesIndexPageSelect<true>;
    'portfolio-index-page': PortfolioIndexPageSelect<false> | PortfolioIndexPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Admin users who can edit site content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Upload images for projects, OG previews, etc. Always add alt text.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for accessibility & SEO.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Service offerings shown across the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Display order, e.g. 01
   */
  number: string;
  name: string;
  /**
   * URL segment, e.g. seo
   */
  slug: string;
  icon:
    | 'Palette'
    | 'Search'
    | 'Globe'
    | 'Layers'
    | 'Smartphone'
    | 'Share2'
    | 'PenTool'
    | 'Code'
    | 'Megaphone'
    | 'Sparkles';
  /**
   * 1-line teaser, e.g. Brand & product design
   */
  short: string;
  /**
   * Punchy hero sentence.
   */
  tagline: string;
  /**
   * Full paragraph shown on the service page.
   */
  description: string;
  features?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  process?:
    | {
        step: string;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  deliverables?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  tools?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  pricing?:
    | {
        tier: string;
        price: string;
        for: string;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Per-page SEO overrides. Leave empty to fall back to site defaults.
   */
  seo?: {
    /**
     * Browser tab + Google result title. ~50-60 chars works best.
     */
    title?: string | null;
    /**
     * Google snippet. Aim for 140-160 chars, write for the click.
     */
    description?: string | null;
    /**
     * Comma-separated. Low ranking weight but useful for internal tagging.
     */
    keywords?: string | null;
    ogImage?: (number | null) | Media;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Portfolio case studies.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * Lower = shown first
   */
  order: number;
  title: string;
  slug: string;
  client: string;
  year: string;
  category: string;
  /**
   * Service names to display as tags.
   */
  services?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  summary: string;
  description: string;
  challenge: string;
  approach: string;
  outcome: string;
  metrics?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional live link.
   */
  link?: {
    label?: string | null;
    url?: string | null;
  };
  /**
   * Hero image, 16:10 looks best.
   */
  cover?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Per-page SEO overrides. Leave empty to fall back to site defaults.
   */
  seo?: {
    /**
     * Browser tab + Google result title. ~50-60 chars works best.
     */
    title?: string | null;
    /**
     * Google snippet. Aim for 140-160 chars, write for the click.
     */
    description?: string | null;
    /**
     * Comma-separated. Low ranking weight but useful for internal tagging.
     */
    keywords?: string | null;
    ogImage?: (number | null) | Media;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  number?: T;
  name?: T;
  slug?: T;
  icon?: T;
  short?: T;
  tagline?: T;
  description?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  process?:
    | T
    | {
        step?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  deliverables?:
    | T
    | {
        item?: T;
        id?: T;
      };
  tools?:
    | T
    | {
        name?: T;
        id?: T;
      };
  pricing?:
    | T
    | {
        tier?: T;
        price?: T;
        for?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  order?: T;
  title?: T;
  slug?: T;
  client?: T;
  year?: T;
  category?: T;
  services?:
    | T
    | {
        name?: T;
        id?: T;
      };
  summary?: T;
  description?: T;
  challenge?: T;
  approach?: T;
  outcome?: T;
  metrics?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  link?:
    | T
    | {
        label?: T;
        url?: T;
      };
  cover?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Site-wide defaults — used when a page doesn't override.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline: string;
  contactEmail: string;
  /**
   * Shown in navbar badge & footer.
   */
  availability?: string | null;
  defaultTitle: string;
  /**
   * Use %s to inject page title.
   */
  titleTemplate?: string | null;
  defaultDescription: string;
  defaultKeywords?: string | null;
  defaultOgImage?: (number | null) | Media;
  siteUrl: string;
  social?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * SEO meta for the static pages (Home, Services, Work, Studio, Contact).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  home?: {
    /**
     * Browser tab + Google result title. ~50-60 chars works best.
     */
    title?: string | null;
    /**
     * Google snippet. Aim for 140-160 chars, write for the click.
     */
    description?: string | null;
    /**
     * Comma-separated. Low ranking weight but useful for internal tagging.
     */
    keywords?: string | null;
    ogImage?: (number | null) | Media;
    noindex?: boolean | null;
  };
  services?: {
    /**
     * Browser tab + Google result title. ~50-60 chars works best.
     */
    title?: string | null;
    /**
     * Google snippet. Aim for 140-160 chars, write for the click.
     */
    description?: string | null;
    /**
     * Comma-separated. Low ranking weight but useful for internal tagging.
     */
    keywords?: string | null;
    ogImage?: (number | null) | Media;
    noindex?: boolean | null;
  };
  portfolio?: {
    /**
     * Browser tab + Google result title. ~50-60 chars works best.
     */
    title?: string | null;
    /**
     * Google snippet. Aim for 140-160 chars, write for the click.
     */
    description?: string | null;
    /**
     * Comma-separated. Low ranking weight but useful for internal tagging.
     */
    keywords?: string | null;
    ogImage?: (number | null) | Media;
    noindex?: boolean | null;
  };
  about?: {
    /**
     * Browser tab + Google result title. ~50-60 chars works best.
     */
    title?: string | null;
    /**
     * Google snippet. Aim for 140-160 chars, write for the click.
     */
    description?: string | null;
    /**
     * Comma-separated. Low ranking weight but useful for internal tagging.
     */
    keywords?: string | null;
    ogImage?: (number | null) | Media;
    noindex?: boolean | null;
  };
  contact?: {
    /**
     * Browser tab + Google result title. ~50-60 chars works best.
     */
    title?: string | null;
    /**
     * Google snippet. Aim for 140-160 chars, write for the click.
     */
    description?: string | null;
    /**
     * Comma-separated. Low ranking weight but useful for internal tagging.
     */
    keywords?: string | null;
    ogImage?: (number | null) | Media;
    noindex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * All editable content on the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  heroBadge?: string | null;
  heroMeta?: string | null;
  /**
   * Each row becomes a stacked line in the hero headline. Tick 'italic' for accent words.
   */
  heroWords?:
    | {
        text: string;
        /**
         * Render this line in italic muted style
         */
        italic?: boolean | null;
        id?: string | null;
      }[]
    | null;
  heroDescription: string;
  heroPrimaryCTA: {
    label: string;
    href: string;
  };
  heroSecondaryCTA: {
    label: string;
    href: string;
  };
  marqueeEyebrow?: string | null;
  marqueeClients?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  servicesEyebrow?: string | null;
  servicesTitleLineOne?: string | null;
  /**
   * Rendered in italic muted style
   */
  servicesTitleLineTwo?: string | null;
  servicesDescription?: string | null;
  portfolioEyebrow?: string | null;
  portfolioTitleLineOne?: string | null;
  /**
   * Rendered in italic muted style
   */
  portfolioTitleLineTwo?: string | null;
  aboutEyebrow?: string | null;
  aboutBody?: string | null;
  processEyebrow?: string | null;
  processTitleLineOne?: string | null;
  processTitleLineTwo?: string | null;
  processDescription?: string | null;
  processSteps?:
    | {
        step: string;
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  stats?:
    | {
        /**
         * Counter ends at this number
         */
        value: number;
        /**
         * e.g. + or %
         */
        suffix: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  testimonialsEyebrow?: string | null;
  testimonialsTitleLineOne?: string | null;
  testimonialsTitleLineTwo?: string | null;
  testimonials?:
    | {
        quote: string;
        name: string;
        role: string;
        id?: string | null;
      }[]
    | null;
  ctaBadge?: string | null;
  ctaTitleLineOne?: string | null;
  ctaTitleLineTwo?: string | null;
  ctaDescription?: string | null;
  ctaPrimary: {
    label: string;
    href: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Editable content on /about.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  eyebrow?: string | null;
  title: string;
  description?: string | null;
  intro?: string | null;
  principlesEyebrow?: string | null;
  principlesTitle?: string | null;
  principles?:
    | {
        number: string;
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  teamEyebrow?: string | null;
  teamTitle?: string | null;
  team?:
    | {
        name: string;
        role: string;
        /**
         * Optional. Falls back to a stylized initial if empty.
         */
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Editable content on /contact.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  eyebrow?: string | null;
  title: string;
  description?: string | null;
  newBusinessEmail?: string | null;
  /**
   * Newlines preserved.
   */
  studioBlurb?: string | null;
  pressEmail?: string | null;
  /**
   * Service buttons in the contact form.
   */
  services?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  budgets?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  submitLabel?: string | null;
  footerNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Editable hero content on /services.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-index-page".
 */
export interface ServicesIndexPage {
  id: number;
  eyebrow?: string | null;
  title: string;
  description?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Editable hero content on /portfolio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-index-page".
 */
export interface PortfolioIndexPage {
  id: number;
  eyebrow?: string | null;
  title: string;
  description?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  contactEmail?: T;
  availability?: T;
  defaultTitle?: T;
  titleTemplate?: T;
  defaultDescription?: T;
  defaultKeywords?: T;
  defaultOgImage?: T;
  siteUrl?: T;
  social?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  home?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
        noindex?: T;
      };
  services?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
        noindex?: T;
      };
  portfolio?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
        noindex?: T;
      };
  about?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
        noindex?: T;
      };
  contact?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroBadge?: T;
  heroMeta?: T;
  heroWords?:
    | T
    | {
        text?: T;
        italic?: T;
        id?: T;
      };
  heroDescription?: T;
  heroPrimaryCTA?:
    | T
    | {
        label?: T;
        href?: T;
      };
  heroSecondaryCTA?:
    | T
    | {
        label?: T;
        href?: T;
      };
  marqueeEyebrow?: T;
  marqueeClients?:
    | T
    | {
        name?: T;
        id?: T;
      };
  servicesEyebrow?: T;
  servicesTitleLineOne?: T;
  servicesTitleLineTwo?: T;
  servicesDescription?: T;
  portfolioEyebrow?: T;
  portfolioTitleLineOne?: T;
  portfolioTitleLineTwo?: T;
  aboutEyebrow?: T;
  aboutBody?: T;
  processEyebrow?: T;
  processTitleLineOne?: T;
  processTitleLineTwo?: T;
  processDescription?: T;
  processSteps?:
    | T
    | {
        step?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  testimonialsEyebrow?: T;
  testimonialsTitleLineOne?: T;
  testimonialsTitleLineTwo?: T;
  testimonials?:
    | T
    | {
        quote?: T;
        name?: T;
        role?: T;
        id?: T;
      };
  ctaBadge?: T;
  ctaTitleLineOne?: T;
  ctaTitleLineTwo?: T;
  ctaDescription?: T;
  ctaPrimary?:
    | T
    | {
        label?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  description?: T;
  intro?: T;
  principlesEyebrow?: T;
  principlesTitle?: T;
  principles?:
    | T
    | {
        number?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  teamEyebrow?: T;
  teamTitle?: T;
  team?:
    | T
    | {
        name?: T;
        role?: T;
        photo?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  description?: T;
  newBusinessEmail?: T;
  studioBlurb?: T;
  pressEmail?: T;
  services?:
    | T
    | {
        label?: T;
        id?: T;
      };
  budgets?:
    | T
    | {
        label?: T;
        id?: T;
      };
  submitLabel?: T;
  footerNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-index-page_select".
 */
export interface ServicesIndexPageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-index-page_select".
 */
export interface PortfolioIndexPageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}